# Generated by Django 5.0.1 on 2026-02-03 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_code', models.CharField(max_length=100, unique=True, verbose_name='서버코드')),
                ('asset_name', models.CharField(max_length=200, verbose_name='자산명')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='상태')),
                ('acg', models.CharField(blank=True, max_length=100, verbose_name='ACG')),
                ('os', models.CharField(blank=True, max_length=100, verbose_name='OS')),
                ('private_ip', models.CharField(blank=True, max_length=50, verbose_name='사설IP')),
                ('public_ip', models.CharField(blank=True, max_length=50, verbose_name='공인IP')),
                ('vpn_ip', models.CharField(blank=True, max_length=50, verbose_name='VPN IP')),
                ('internet_facing', models.BooleanField(default=False, verbose_name='인터넷 접점여부')),
                ('service_category', models.CharField(blank=True, max_length=100, verbose_name='서비스 대분류')),
                ('service_subcategory', models.CharField(blank=True, max_length=100, verbose_name='서비스 소분류')),
                ('asset_location', models.CharField(blank=True, max_length=200, verbose_name='자산위치')),
                ('detailed_location', models.CharField(blank=True, max_length=200, verbose_name='세부위치')),
                ('specs', models.TextField(blank=True, verbose_name='스펙')),
                ('manager', models.CharField(blank=True, max_length=100, verbose_name='담당자')),
                ('administrator', models.CharField(blank=True, max_length=100, verbose_name='관리자')),
                ('management_department', models.CharField(blank=True, max_length=100, verbose_name='관리부서')),
                ('confidentiality', models.CharField(blank=True, max_length=50, verbose_name='기밀성')),
                ('integrity', models.CharField(blank=True, max_length=50, verbose_name='무결성')),
                ('availability', models.CharField(blank=True, max_length=50, verbose_name='가용성')),
                ('importance_score', models.IntegerField(blank=True, null=True, verbose_name='중요도 점수')),
                ('importance_grade', models.CharField(blank=True, max_length=50, verbose_name='중요도 등급')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('model_version', models.CharField(blank=True, max_length=200, verbose_name='모델 및 버전')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='최종 수정일자')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '서버 자산',
                'verbose_name_plural': '서버 자산 목록',
                'db_table': 'server_assets',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='변경 일시')),
                ('field_name', models.CharField(max_length=100, verbose_name='변경 필드')),
                ('old_value', models.TextField(blank=True, verbose_name='이전 값')),
                ('new_value', models.TextField(blank=True, verbose_name='새로운 값')),
                ('change_type', models.CharField(choices=[('CREATE', '생성'), ('UPDATE', '수정'), ('DELETE', '삭제')], max_length=10, verbose_name='변경 타입')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='변경 사용자')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_histories', to='assets.serverasset', verbose_name='서버 자산')),
            ],
            options={
                'verbose_name': '변경 이력',
                'verbose_name_plural': '변경 이력 목록',
                'db_table': 'change_history',
                'ordering': ['-changed_at'],
            },
        ),
    ]
