# Generated by Django 5.0.1 on 2026-02-04 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='필드명')),
                ('field_key', models.CharField(max_length=100, unique=True, verbose_name='필드 키')),
                ('field_type', models.CharField(choices=[('text', '텍스트'), ('number', '숫자'), ('date', '날짜'), ('boolean', '예/아니오'), ('select', '선택 목록')], default='text', max_length=20, verbose_name='필드 타입')),
                ('is_required', models.BooleanField(default=False, verbose_name='필수 여부')),
                ('display_order', models.IntegerField(default=0, verbose_name='표시 순서')),
                ('options', models.TextField(blank=True, help_text='선택 목록 타입일 경우, 쉼표로 구분하여 입력', verbose_name='선택 옵션')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '사용자 정의 필드',
                'verbose_name_plural': '사용자 정의 필드 목록',
                'db_table': 'custom_fields',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, verbose_name='값')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='assets.serverasset', verbose_name='서버 자산')),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='assets.customfield', verbose_name='사용자 정의 필드')),
            ],
            options={
                'verbose_name': '사용자 정의 필드 값',
                'verbose_name_plural': '사용자 정의 필드 값 목록',
                'db_table': 'custom_field_values',
                'unique_together': {('asset', 'custom_field')},
            },
        ),
    ]
