# Generated by Django 5.0.1 on 2026-02-04 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_customfield_customfieldvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changehistory',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_histories', to='assets.serverasset', verbose_name='서버 자산'),
        ),
    ]
