# Generated by Django 5.0.1 on 2026-02-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_changehistory_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverasset',
            name='display_order',
            field=models.IntegerField(db_index=True, default=0, verbose_name='표시 순서'),
        ),
    ]
