# Generated by Django 5.0.1 on 2026-02-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_serverasset_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverasset',
            name='internet_facing',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='인터넷 접점여부'),
        ),
    ]
