# Generated by Django 5.0.1 on 2026-02-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_allow_null_internet_facing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverasset',
            name='server_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='서버코드'),
        ),
    ]
